config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :items do
    collection do
      post :import
    end
  end
  root to: 'items#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    belongs_to :item, foreign_key: "item_id"
    has_one_attached :image
end

app/models/item.rb
class Item < ApplicationRecord 
    validates_presence_of :brand
    validates_presence_of :price
    validates_presence_of :quantity
    validates_presence_of :country
    validates_presence_of :colour
    validates_presence_of :company_name
    validates_presence_of :model
    validates_presence_of :other_spec

    has_one :customer, dependent: :destroy   
    scope :join_customer_table, -> {joins("INNER JOIN customers ON customers.item_id = items.id")}

    def self.item_import(file)
        sheet = self.open_sheet(file)
        if sheet
            (sheet.sheets).map do |i|
                brand = ['brand', sheet.cell(3, 'B', i)]
                price = ['price', sheet.cell(3,'E',i)]
                quantity = ['quantity', sheet.cell(3, 'H', i)]
                country = ['country', sheet.cell(6, 'B', i)]
                colour = ['colour', sheet.cell(4, 'E', i)]
                company_name = ['company_name', sheet.cell(5, 'B', i)]
                model = ['model', sheet.cell(4, 'B', i)]
                other_spec = ['other_spec', sheet.cell(7, 'B', i)]
                item_data = Hash[[brand, price, quantity, country, colour, company_name, model, other_spec]]
                
                images = sheet.images(i)[0]
                name = sheet.cell(9, 'B', i).present? ? sheet.cell(9, 'B', i).split(' ') : []
                last_name = ['last_name' , name[1]]
                first_name = ['first_name' , name[0]]
                ph_num = ['ph_num' , sheet.cell(11, 'B', i)]
                email = ['email' , sheet.cell(10, 'B', i)]
                customer_data = Hash[[last_name, first_name, ph_num, email]]
    
                create_item(item_data, customer_data, images)
            end
        else
            false
        end
    end

    def self.create_item(data1, data2, image = nil)
        item = Item.find_by(brand: data1['brand']) || new
        item.attributes = data1
        if item.save
            if Customer.find_by(item_id: item.id)
                item.customer.update(data2)
            else
                item.create_customer(data2)
            end
            item.customer.image.attach(io: File.open(image),filename: "customer#{data2['last_name']}.jpg", content_type: 'image/jpeg') if image.present?
        else
            false
        end
    end

    def self.open_sheet(file)
        if file.present?
            case File.extname(file.original_filename)
            when ".csv" then Csv.new(file.path, nil, :ignore)
            when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
            when ".xlsx" then Roo::Excelx.new(file.path)
            else raise "Unknown file type: #{file.original_filename}"
            end
        else
            false
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:ph_num, :email, :last_name, :first_name, :birthday, :image)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.join_customer_table.order('customers.item_id')
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename=template.xlsx"
      }
      format.html { render :index }
    end
  end

  def import
    Item.item_import(params[:file])
    redirect_to items_url
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.fetch(:item, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="container-fluid">
  <p id="notice"><%= notice %></p>

  <h1>Items</h1>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Brand</th>
        <th>Country</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Customer Name</th>
        <th>Email</th>
        <th>Phone number</th>
        <th>Photo</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.brand %></td>
          <td><%= item.country %></td>
          <td><%= item.price %></td>
          <td><%= item.quantity %></td>
          <td><%= "#{item.customer.first_name}  #{item.customer.last_name}" %></td>
          <td><%= item.customer.email %></td>
          <td><%= item.customer.ph_num %></td>
          <td><%= image_tag item.customer.image , style: 'height:100px; width:auto;' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to 'Download Excel Template', items_path(format: :xlsx),:class => "btn btn btn-info text-white" %>
  <h4 class="my-3">Import Items</h4> 
  <%= form_with url: import_items_path, local: true do |form| %>
    <%= form.file_field :file %>
    <%= form.submit "Import", :class => "btn btn-success text-white" %>
  <% end %>
  <%# link_to 'New Item', new_item_path %>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UploadImgExcel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>